### ISSUE TITLE
Flixster Feedback

### ISSUE THREAD

**Issue by taylorledingham** [chaytanc/metaU#3]
We will cover this in our 1-1 but wanted to provide some feedback on the code so far:
- https://github.com/chaytanc/metaU/blob/main/Flixster/Flixster/CollectionViewController.m#L21 - When naming your classes/files please use more specific names. ie - MovieListCollectionViewController. Naming helps explains to the reviewer what the class does.
- https://github.com/chaytanc/metaU/blob/main/Flixster/Flixster/CollectionViewController.m#L36 - I would recommend moving this network code to its own function and then call that function inside viewdidLoad
- https://github.com/chaytanc/metaU/blob/main/Flixster/Flixster/CollectionViewController.m#L40 - So whenever we make an async network call we should create a dispatch block to the main thread so we aren't blocking the main thread. https://riptutorial.com/ios/example/27493/getting-the-main-queue 
- https://github.com/chaytanc/metaU/blob/main/Flixster/Flixster/CollectionViewController.m#L69 - function name to describe what its doing so something "presentErrorAlert"
- https://github.com/chaytanc/metaU/blob/main/Flixster/Flixster/CollectionViewController.m#L110 - since this function is repeating alot of the code you had in viewdidLoad you might want to create a helper function so both places (first load and refresh) can reuse the same code.

**Comment by chaytanc** [comment]
-  Fixed ambiguous collection names
- Made fetchMovies func
- Added dispatch block but not entirely sure I implemented it correctly
- Fixed networkerror function name
- Refactored fetchMovies to have isRefresh parameter so that less code is repeated in beginRefresh
